[project]
name = "data_catalog"
version = "0.0.1"
description = "Central data catalog managed with pydantic"
authors = [
    {name="Joshua Marango", email="hello@joshuamarango.com"}
]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "pydantic"
]
